import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react';
import { designsystems } from "./api/designsystems";
import styles from '../styles/Home.module.css'
import { CgMenuGridR, CgMenu } from 'react-icons/fa';

export const getStaticProps = async () => {
  return {
    props: {
      designsystems: designsystems
    }
  }
}



export default function Home({ designsystems }) {
  const [toggleViewMode, setToggleViewMode] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Norwegian Design Systems</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo}>
          <Image src="/images/aurora.svg" alt="cover" width="256" height="190" />
        </div>

        <h1 className={styles.title}>
          Norwegian Design Systems
        </h1>

        <p className={styles.description}>
          A curated list of design systems, pattern libraries and style guides from Norway.
        </p>

        <div className="{styles.filter}">
          Sort [Select] <br/>
          Filter [all] <br/>
          Search
          <button
              className={styles.toggleViewButton}
              onClick={() => setToggleViewMode(!toggleViewMode)}
          >
            {toggleViewMode ? 'Grid' : 'List'}
          </button>
        </div>

        <div className={styles.layout + ' ' + `${toggleViewMode ? styles.layoutGrid : styles.layoutList}`}>
          { designsystems.map(designsystem => (
            <div className={styles.card} key={designsystem?.name}>
              <div>
                {designsystem?.company &&
                    <span className={styles.company}>{designsystem.company}</span>
                }
                {designsystem?.logo &&
                    <Image src={designsystem.logo} width="24" height="24" alt={'Logo'} />
                }
              </div>
              <a href={designsystem?.url} target="_blank" rel="noreferrer">
                <h2>{designsystem.name}</h2>
              </a>

              {designsystem?.repo?.name &&
                <div>{designsystem.repo.name}</div>
              }
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <h2>Credits</h2>
        <p>
        Thanks to <a href="https://github.com/alexpate">alexpate</a> for inspiration and a fantastic list of <a
          href="https://github.com/alexpate/awesome-design-systems">awesome design systems</a>.
        </p>
      </footer>
    </div>
  )
}
