import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { designsystems } from './api/designsystems';
import { CgMenuGridR, CgMenu } from 'react-icons/fa';

export const getStaticProps = async () => {
  return {
    props: {
      designsystems: designsystems,
    },
  };
};
export default function Home({ designsystems }) {
  const [toggleViewMode, setToggleViewMode] = useState(false);

  return (
    <div className="nds-container">
      <Head>
        <title>Norwegian Design Systems</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <main className="main">
        <div className="logo">
          <Image src="/images/aurora.svg" alt="cover" width="256" height="190" />
        </div>

        <h1 className="title">Norwegian Design Systems</h1>

        <p className="description">
          A curated list of design systems, pattern libraries and style guides from Norway.
        </p>

        <div className="filter">
          Sort [Select] <br />
          Filter [all] <br />
          Search
          <button className="toggleViewButton" onClick={() => setToggleViewMode(!toggleViewMode)}>
            {toggleViewMode ? 'Grid' : 'List'}
          </button>
        </div>

        <ul
          className={'nds-layout' + ' ' + `${toggleViewMode ? 'nds-layoutGrid' : 'nds-layoutList'}`}
        >
          {designsystems.map(designsystem => (
            <li key={designsystem?.name} className="nds-layoutItem">
              <article className="nds-card">
                <div>
                  {designsystem?.company && <span className="company">{designsystem.company}</span>}
                  {designsystem?.logo && (
                    <Image src={designsystem.logo} width="24" height="24" alt={'Logo'} />
                  )}
                </div>
                <a href={designsystem?.url} target="_blank" rel="noreferrer">
                  <h2>{designsystem.name}</h2>
                </a>

                {designsystem?.repo?.name && <footer>{designsystem.repo.name}</footer>}
              </article>
            </li>
          ))}
        </ul>
      </main>

      <footer className="nds-footer">
        <p>
          Made with ❤️ in 🇳🇴 by Ronny Siikaluoma • <a href="https://twitter.com/siiron">Twitter</a>{' '}
          • <a href="https://www.linkedin.com/in/ronnysiikaluoma/">LinkedIn</a>
        </p>
        <h2>Thanks to</h2>
        <p>
          <a href="https://github.com/alexpate">alexpate</a> for inspiration and a fantastic list of{' '}
          <a href="https://github.com/alexpate/awesome-design-systems">awesome design systems</a>
        </p>
      </footer>
    </div>
  );
}
